### ISSUE TITLE
Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR 

### ISSUE THREAD

**Issue by tandage** [lengstrom/fast-style-transfer#263]
hi, when I get the env ready and type in the script  _python evaluate.py --checkpoint C:\Users\hasee\fast-style-transfer\examples\style\la_muse.ckpt --in-path C:\Users\hasee\fast-style-transfer\examples\content\chicago.jpg --out-path C:\Users\hasee\fast-style-transfer\examples\result\chicago.jpg_, it thorws some errors.

**WARNING:tensorflow:From F:\anaconda\envs\tf-gpu\lib\site-packages\tensorflow_core\python\ops\resource_variable_ops.py:1635: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:**

2021-02-24 09:29:24.097223: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] **Could not create cudnn handle:** CUDNN_STATUS_INTERNAL_ERROR

  (0) Unknown: **Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.**
         [[{{node Conv2D}}]]
         [[add_37/_99]]

**Errors may have originated from an input operation.**

I have no idea where is wrong, and how to fix

**Comment by tandage** [comment]
![image](https://user-images.githubusercontent.com/64976499/108932513-7378f680-7684-11eb-81e4-01c7f9fb9c7b.png)
![image](https://user-images.githubusercontent.com/64976499/108932529-7bd13180-7684-11eb-80f9-54ec70571006.png)

**Comment by tandage** [comment]
python evaluate.py --checkpoint C:\Users\hasee\fast-style-transfer\examples\style\la_muse.ckpt --in-path C:\Users\hasee\fast-style-transfer\examples\content\chicago.jpg --out-path C:\Users\hasee\fast-style-transfer\examples\results\chicago.jpg

**Comment by tandage** [comment]
above line is the input script

**Comment by impactcolor** [comment]
@tandage any progress on this?

**Comment by noahebrown** [comment]
For anyone else with this issue this solved it for me 
Add `tf.compat.v1.disable_v2_behavior()` before the tensorflow GPU session creation in optimize.py
